### ISSUE TITLE
Since the new update , I can't seem to understand the new generated code 

### ISSUE THREAD

**Issue by medamine-elleuch** [kat-tax/figma-to-react-native#18]
Hello, First I want to thank you for the effort made in making this plugin. It is a lifesaver and made my work a lot faster. 
Since the new update of "Version 43 on October 25, 2023" the generated code has changed significantly. 
I made a repo with the same component-generated code one with the old version and the other with the new one. 
https://github.com/mdaster/figma-to-react-native-bug
With the new updated version, I have problems with : 
- import {useStyles, createStyles} from 'styles';
- theme 
- the props used to be enum 
- What used to be JSX.Element is now ReactElement 
PS: I'm using Expo Framework to create Cross-Platform apps using react-native and TS 
Would it be possible to add in the plugin options what version of plugin I want to use? That way I and many other developers won't be having any future problems.
Thank You.

**Comment by TheUltDev** [comment]
I will keep this in mind going forward. When the plugin is more mature I will add versioning, but currently it would be too difficult to maintain each version and fix bugs for all of them.

You can however checkout the repo, use the tag `v42`, build the plugin, import the manifest, and run your own copy at whatever version you want.

First I'll start with the minor things:

> the props used to be enum

Do you prefer enums? I switched from enums to aliases since they are more compact and make it easier to use the component (you don't have to import the enums)

> What used to be JSX.Element is now ReactElement

Correct, is there an issue with this? I just made it a bit more specific type.

> import {useStyles, createStyles} from 'styles';

This is the new theme system using Unistyles. It's undocumented and not included in the download right now (I will fix this soon) so I understand your confusion. Basically you will want put these files in your source folder root:

theme.ts
```
<theme file generated by the plugin>
```

styles.ts
```ts
import {createUnistyles} from 'react-native-unistyles';
import {breakpoints} from 'theme';

export const {createStyles, useStyles} = createUnistyles(breakpoints);
```

(Make sure to install `react-native-unistyles`)

**Comment by medamine-elleuch** [comment]
Hello again, Unfortunately, your latest reply hasn't helped in fixing most of the errors I'm having. You can find them attached below. 

- Switching to aliases is much better than enums like you said it will make using the component much faster and more elegant. 
- I followed your instructions and did install react-native-unistyles but I have an error in "createStyles" now.

PS: I didn't have any of these errors in the last generated code version 42 :( ( Like I said before it used to work perfectly fine so don't mind checking the repo : https://github.com/mdaster/figma-to-react-native-bug )

- I'd love to build the v42 but I don't know where to start ? so any tips?

![Screenshot 2023-10-26 225448](https://github.com/kat-tax/figma-to-react-native/assets/61760953/ebfa2ceb-706e-4203-80ac-4deabfbc722f)
![Screenshot 2023-10-26 225534](https://github.com/kat-tax/figma-to-react-native/assets/61760953/603e6c75-ef3d-4d44-97d2-1499e4266967)
![Screenshot 2023-10-26 225554](https://github.com/kat-tax/figma-to-react-native/assets/61760953/3473fab6-b506-4ad7-8d51-094cc2667ac1)
![Screenshot 2023-10-26 225607](https://github.com/kat-tax/figma-to-react-native/assets/61760953/5dbe0510-bfd6-45e7-bc83-e16162f694d7)

Thank you.

**Comment by TheUltDev** [comment]
@mdaster I gave you an outdated exampled for unistyles. I will update the example after work.
For `ReactElement` that's a bug, it should be `React.ReactElement` I will fix that in a patch this weekend.

**Comment by medamine-elleuch** [comment]
At last , I was able to build v42 and run it as a figma plugin. I have to say it was kinda a complex task for a first timer 😂 but with a little expert help nothing is impossible.
Keep up the good work 💯👍🏻
